import Foundation

enum L10n {
    static func resolvedLanguage(for preference: AppLanguagePreference) -> ResolvedLanguage {
        switch preference {
        case .english:
            return .english
        case .simplifiedChinese:
            return .simplifiedChinese
        case .japanese:
            return .japanese
        case .automatic:
            return inferLanguage()
        }
    }

    static func inferLanguage() -> ResolvedLanguage {
        let preferred = Locale.preferredLanguages.first ?? ""
        let languageCode = Locale(identifier: preferred).language.languageCode?.identifier.lowercased() ?? ""
        let regionCode = Locale.current.region?.identifier.uppercased() ?? ""

        if languageCode == "ja" {
            return .japanese
        }
        if languageCode == "zh" || ["CN", "HK", "MO", "TW", "SG"].contains(regionCode) {
            return .simplifiedChinese
        }
        return .english
    }

    static func text(_ key: String, language: ResolvedLanguage) -> String {
        let table: [String: String]
        switch language {
        case .english:
            table = en
        case .simplifiedChinese:
            table = zh
        case .japanese:
            table = ja
        }
        return table[key] ?? en[key] ?? key
    }

    private static let en: [String: String] = [
        "tab.calculate": "Calculate",
        "tab.history": "History",
        "tab.notes": "Notes",
        "tab.tools": "Tools",
        "tab.settings": "Settings",
        "common.calculate": "Calculate",
        "common.save": "Save",
        "common.cancel": "Cancel",
        "common.done": "Done",
        "common.delete": "Delete",
        "common.edit": "Edit",
        "common.copy": "Copy",
        "common.restore": "Restore",
        "common.unlock": "Unlock Pro",
        "common.free": "Free",
        "common.pro": "Pro",
        "common.result": "Result",
        "common.expression": "Expression",
        "common.error": "Error",
        "common.saved": "Saved",
        "common.favorite": "Favorite",
        "common.unfavorite": "Unfavorite",
        "common.empty": "Empty",
        "common.required": "Required",
        "common.invalidNumber": "Enter a valid number.",
        "common.share": "Share",
        "calculate.title": "FormulaPad",
        "calculate.subtitle": "Type a formula, reuse variables, keep the result.",
        "calculate.placeholder": "20000 * (1 + 0.035)^3",
        "calculate.variableTitle": "Variables",
        "calculate.noVariables": "No variables yet.",
        "calculate.saveNote": "Save Note",
        "calculate.clear": "Clear",
        "calculate.angle": "Angle",
        "calculate.degrees": "Degrees",
        "calculate.radians": "Radians",
        "calculate.invalidExpression": "This formula could not be calculated.",
        "calculate.copied": "Copied result.",
        "history.title": "History",
        "history.empty": "Your calculations will appear here.",
        "history.reuse": "Reuse",
        "history.clearAll": "Clear All",
        "history.limit": "Free history keeps the latest 20 items.",
        "notes.title": "Math Notes",
        "notes.empty": "Saved notes will appear here.",
        "notes.titleField": "Title",
        "notes.titlePlaceholder": "Homework, estimate, formula...",
        "notes.remarks": "Remarks",
        "notes.remarksPlaceholder": "Add context or steps.",
        "notes.category": "Category",
        "notes.validationTitle": "Add a title before saving.",
        "category.study": "Study",
        "category.work": "Work",
        "category.life": "Life",
        "category.finance": "Finance",
        "tools.segment.templates": "Templates",
        "tools.segment.convert": "Convert",
        "tools.segment.plot": "Plot",
        "templates.title": "Templates",
        "templates.calculate": "Use Template",
        "templates.saveHistory": "Save to History",
        "templates.resultSaved": "Template result saved.",
        "template.percent.title": "Percentage",
        "template.percent.subtitle": "Part as a percentage of whole",
        "template.percent.part": "Part",
        "template.percent.whole": "Whole",
        "template.percent.explanation": "Part divided by whole, then multiplied by 100.",
        "template.discount.title": "Discount",
        "template.discount.subtitle": "Sale price after discount",
        "template.discount.price": "Original price",
        "template.discount.rate": "Discount %",
        "template.discount.explanation": "Original price multiplied by the remaining percentage.",
        "template.compound.title": "Compound Interest",
        "template.compound.subtitle": "Future value over years",
        "template.compound.principal": "Principal",
        "template.compound.rate": "Annual rate %",
        "template.compound.years": "Years",
        "template.compound.explanation": "Principal multiplied by one plus annual rate raised to years.",
        "template.loan.title": "Loan Payment",
        "template.loan.subtitle": "Estimated monthly payment",
        "template.loan.amount": "Loan amount",
        "template.loan.rate": "Annual rate %",
        "template.loan.months": "Months",
        "template.loan.explanation": "Uses the standard amortized monthly payment formula.",
        "template.bmi.title": "BMI",
        "template.bmi.subtitle": "Body mass index",
        "template.bmi.weight": "Weight kg",
        "template.bmi.height": "Height m",
        "template.bmi.explanation": "Weight divided by height squared.",
        "template.average.title": "Average",
        "template.average.subtitle": "Mean of comma-separated values",
        "template.average.values": "Values",
        "template.average.explanation": "Sum of values divided by count.",
        "template.triangle.title": "Triangle Area",
        "template.triangle.subtitle": "Base and height",
        "template.triangle.base": "Base",
        "template.triangle.height": "Height",
        "template.triangle.explanation": "Base multiplied by height, then divided by 2.",
        "template.speed.title": "Speed",
        "template.speed.subtitle": "Distance over time",
        "template.speed.distance": "Distance",
        "template.speed.time": "Time",
        "template.speed.explanation": "Distance divided by time.",
        "convert.title": "Unit Converter",
        "convert.value": "Value",
        "convert.from": "From",
        "convert.to": "To",
        "convert.category": "Category",
        "convert.save": "Save Conversion",
        "convert.saved": "Conversion saved.",
        "unit.length": "Length",
        "unit.weight": "Weight",
        "unit.area": "Area",
        "unit.volume": "Volume",
        "unit.temperature": "Temperature",
        "unit.time": "Time",
        "unit.speed": "Speed",
        "unit.meter": "Meter",
        "unit.kilometer": "Kilometer",
        "unit.centimeter": "Centimeter",
        "unit.mile": "Mile",
        "unit.foot": "Foot",
        "unit.kilogram": "Kilogram",
        "unit.gram": "Gram",
        "unit.pound": "Pound",
        "unit.squareMeter": "Square meter",
        "unit.squareFoot": "Square foot",
        "unit.acre": "Acre",
        "unit.liter": "Liter",
        "unit.milliliter": "Milliliter",
        "unit.gallon": "Gallon",
        "unit.celsius": "Celsius",
        "unit.fahrenheit": "Fahrenheit",
        "unit.kelvin": "Kelvin",
        "unit.second": "Second",
        "unit.minute": "Minute",
        "unit.hour": "Hour",
        "unit.mps": "m/s",
        "unit.kph": "km/h",
        "unit.mph": "mph",
        "plot.title": "Function Plot",
        "plot.placeholder": "x^2 or sin(x)",
        "plot.range": "x from -10 to 10",
        "plot.draw": "Plot",
        "plot.save": "Save Plot",
        "plot.saved": "Plot saved.",
        "plot.invalid": "Enter a function that uses x.",
        "pro.title": "FormulaPad Pro",
        "pro.subtitle": "One-time unlock for complete math notes.",
        "pro.body": "Unlock unlimited history, notes, custom formulas, full templates, plotting, and export.",
        "pro.once": "One-time purchase",
        "pro.loading": "Loading purchase...",
        "pro.unavailable": "Purchase is unavailable right now.",
        "pro.owned": "Pro is unlocked.",
        "pro.restoreDone": "Purchases restored.",
        "settings.title": "Settings",
        "settings.language": "Language",
        "settings.language.auto": "Automatic",
        "settings.language.en": "English",
        "settings.language.zh": "Simplified Chinese",
        "settings.language.ja": "Japanese",
        "settings.privacy": "Privacy Policy",
        "settings.support": "Support",
        "settings.contact": "Contact Support",
        "settings.version": "Version 1.0.0",
        "settings.local": "Local data only",
        "share.note": "FormulaPad calculation",
        "error.divideByZero": "Division by zero.",
        "error.syntax": "Check the formula syntax.",
        "error.unknownVariable": "Unknown variable.",
        "error.invalidAssignment": "Invalid assignment.",
        "error.domain": "The value is outside the supported range."
    ]

    private static let zh: [String: String] = [
        "tab.calculate": "计算",
        "tab.history": "历史",
        "tab.notes": "笔记",
        "tab.tools": "工具",
        "tab.settings": "设置",
        "common.calculate": "计算",
        "common.save": "保存",
        "common.cancel": "取消",
        "common.done": "完成",
        "common.delete": "删除",
        "common.edit": "编辑",
        "common.copy": "复制",
        "common.restore": "恢复购买",
        "common.unlock": "解锁 Pro",
        "common.free": "免费",
        "common.pro": "Pro",
        "common.result": "结果",
        "common.expression": "公式",
        "common.error": "错误",
        "common.saved": "已保存",
        "common.favorite": "收藏",
        "common.unfavorite": "取消收藏",
        "common.empty": "暂无内容",
        "common.required": "必填",
        "common.invalidNumber": "请输入有效数字。",
        "common.share": "分享",
        "calculate.title": "算记",
        "calculate.subtitle": "输入公式、复用变量、保存结果。",
        "calculate.placeholder": "20000 * (1 + 0.035)^3",
        "calculate.variableTitle": "变量",
        "calculate.noVariables": "还没有变量。",
        "calculate.saveNote": "保存为笔记",
        "calculate.clear": "清空",
        "calculate.angle": "角度",
        "calculate.degrees": "角度制",
        "calculate.radians": "弧度制",
        "calculate.invalidExpression": "无法计算这个公式。",
        "calculate.copied": "结果已复制。",
        "history.title": "历史",
        "history.empty": "计算结果会显示在这里。",
        "history.reuse": "复用",
        "history.clearAll": "清空全部",
        "history.limit": "免费版保留最近 20 条历史。",
        "notes.title": "数学笔记",
        "notes.empty": "保存的笔记会显示在这里。",
        "notes.titleField": "标题",
        "notes.titlePlaceholder": "作业、估算、公式...",
        "notes.remarks": "备注",
        "notes.remarksPlaceholder": "补充用途或步骤。",
        "notes.category": "分类",
        "notes.validationTitle": "保存前请填写标题。",
        "category.study": "学习",
        "category.work": "工作",
        "category.life": "生活",
        "category.finance": "财务",
        "tools.segment.templates": "模板",
        "tools.segment.convert": "换算",
        "tools.segment.plot": "图像",
        "templates.title": "公式模板",
        "templates.calculate": "使用模板",
        "templates.saveHistory": "保存到历史",
        "templates.resultSaved": "模板结果已保存。",
        "template.percent.title": "百分比",
        "template.percent.subtitle": "部分占整体的比例",
        "template.percent.part": "部分",
        "template.percent.whole": "整体",
        "template.percent.explanation": "部分除以整体，再乘以 100。",
        "template.discount.title": "折扣",
        "template.discount.subtitle": "折后价格",
        "template.discount.price": "原价",
        "template.discount.rate": "折扣 %",
        "template.discount.explanation": "原价乘以剩余比例。",
        "template.compound.title": "复利",
        "template.compound.subtitle": "多年后的本息",
        "template.compound.principal": "本金",
        "template.compound.rate": "年化 %",
        "template.compound.years": "年数",
        "template.compound.explanation": "本金乘以一加年化收益率的年数次方。",
        "template.loan.title": "贷款月供",
        "template.loan.subtitle": "估算每月还款",
        "template.loan.amount": "贷款金额",
        "template.loan.rate": "年利率 %",
        "template.loan.months": "期数（月）",
        "template.loan.explanation": "使用等额本息月供公式估算。",
        "template.bmi.title": "BMI",
        "template.bmi.subtitle": "身体质量指数",
        "template.bmi.weight": "体重 kg",
        "template.bmi.height": "身高 m",
        "template.bmi.explanation": "体重除以身高的平方。",
        "template.average.title": "平均数",
        "template.average.subtitle": "逗号分隔数字的均值",
        "template.average.values": "数字",
        "template.average.explanation": "所有数字求和后除以数量。",
        "template.triangle.title": "三角形面积",
        "template.triangle.subtitle": "底和高",
        "template.triangle.base": "底",
        "template.triangle.height": "高",
        "template.triangle.explanation": "底乘以高，再除以 2。",
        "template.speed.title": "速度",
        "template.speed.subtitle": "距离除以时间",
        "template.speed.distance": "距离",
        "template.speed.time": "时间",
        "template.speed.explanation": "距离除以时间。",
        "convert.title": "单位换算",
        "convert.value": "数值",
        "convert.from": "从",
        "convert.to": "到",
        "convert.category": "分类",
        "convert.save": "保存换算",
        "convert.saved": "换算已保存。",
        "unit.length": "长度",
        "unit.weight": "重量",
        "unit.area": "面积",
        "unit.volume": "体积",
        "unit.temperature": "温度",
        "unit.time": "时间",
        "unit.speed": "速度",
        "unit.meter": "米",
        "unit.kilometer": "千米",
        "unit.centimeter": "厘米",
        "unit.mile": "英里",
        "unit.foot": "英尺",
        "unit.kilogram": "千克",
        "unit.gram": "克",
        "unit.pound": "磅",
        "unit.squareMeter": "平方米",
        "unit.squareFoot": "平方英尺",
        "unit.acre": "英亩",
        "unit.liter": "升",
        "unit.milliliter": "毫升",
        "unit.gallon": "加仑",
        "unit.celsius": "摄氏度",
        "unit.fahrenheit": "华氏度",
        "unit.kelvin": "开尔文",
        "unit.second": "秒",
        "unit.minute": "分钟",
        "unit.hour": "小时",
        "unit.mps": "米/秒",
        "unit.kph": "千米/小时",
        "unit.mph": "英里/小时",
        "plot.title": "函数图像",
        "plot.placeholder": "x^2 或 sin(x)",
        "plot.range": "x 从 -10 到 10",
        "plot.draw": "绘制",
        "plot.save": "保存图像",
        "plot.saved": "图像已保存。",
        "plot.invalid": "请输入包含 x 的函数。",
        "pro.title": "FormulaPad Pro",
        "pro.subtitle": "一次购买，解锁完整数学笔记。",
        "pro.body": "解锁无限历史、笔记、自定义公式、完整模板、函数图像和导出。",
        "pro.once": "一次性购买",
        "pro.loading": "正在载入购买项目...",
        "pro.unavailable": "当前无法购买。",
        "pro.owned": "Pro 已解锁。",
        "pro.restoreDone": "购买已恢复。",
        "settings.title": "设置",
        "settings.language": "语言",
        "settings.language.auto": "自动",
        "settings.language.en": "English",
        "settings.language.zh": "简体中文",
        "settings.language.ja": "日本語",
        "settings.privacy": "隐私政策",
        "settings.support": "支持",
        "settings.contact": "联系支持",
        "settings.version": "版本 1.0.0",
        "settings.local": "仅本地数据",
        "share.note": "FormulaPad 计算",
        "error.divideByZero": "不能除以零。",
        "error.syntax": "请检查公式语法。",
        "error.unknownVariable": "未知变量。",
        "error.invalidAssignment": "无效赋值。",
        "error.domain": "数值超出支持范围。"
    ]

    private static let ja: [String: String] = [
        "tab.calculate": "計算",
        "tab.history": "履歴",
        "tab.notes": "メモ",
        "tab.tools": "ツール",
        "tab.settings": "設定",
        "common.calculate": "計算",
        "common.save": "保存",
        "common.cancel": "キャンセル",
        "common.done": "完了",
        "common.delete": "削除",
        "common.edit": "編集",
        "common.copy": "コピー",
        "common.restore": "購入を復元",
        "common.unlock": "Pro を解除",
        "common.free": "無料",
        "common.pro": "Pro",
        "common.result": "結果",
        "common.expression": "式",
        "common.error": "エラー",
        "common.saved": "保存済み",
        "common.favorite": "お気に入り",
        "common.unfavorite": "解除",
        "common.empty": "空です",
        "common.required": "必須",
        "common.invalidNumber": "有効な数値を入力してください。",
        "common.share": "共有",
        "calculate.title": "数式メモ",
        "calculate.subtitle": "式を入力し、変数を使い、結果を残せます。",
        "calculate.placeholder": "20000 * (1 + 0.035)^3",
        "calculate.variableTitle": "変数",
        "calculate.noVariables": "変数はまだありません。",
        "calculate.saveNote": "メモに保存",
        "calculate.clear": "クリア",
        "calculate.angle": "角度",
        "calculate.degrees": "度",
        "calculate.radians": "ラジアン",
        "calculate.invalidExpression": "この式は計算できません。",
        "calculate.copied": "結果をコピーしました。",
        "history.title": "履歴",
        "history.empty": "計算結果がここに表示されます。",
        "history.reuse": "再利用",
        "history.clearAll": "すべて削除",
        "history.limit": "無料版では最新 20 件の履歴を保存します。",
        "notes.title": "数式メモ",
        "notes.empty": "保存したメモがここに表示されます。",
        "notes.titleField": "タイトル",
        "notes.titlePlaceholder": "宿題、見積もり、公式...",
        "notes.remarks": "メモ",
        "notes.remarksPlaceholder": "用途や手順を追加します。",
        "notes.category": "カテゴリ",
        "notes.validationTitle": "保存する前にタイトルを入力してください。",
        "category.study": "学習",
        "category.work": "仕事",
        "category.life": "生活",
        "category.finance": "家計",
        "tools.segment.templates": "テンプレート",
        "tools.segment.convert": "換算",
        "tools.segment.plot": "グラフ",
        "templates.title": "数式テンプレート",
        "templates.calculate": "テンプレートを使用",
        "templates.saveHistory": "履歴に保存",
        "templates.resultSaved": "テンプレート結果を保存しました。",
        "template.percent.title": "パーセント",
        "template.percent.subtitle": "全体に対する割合",
        "template.percent.part": "部分",
        "template.percent.whole": "全体",
        "template.percent.explanation": "部分を全体で割り、100 を掛けます。",
        "template.discount.title": "割引",
        "template.discount.subtitle": "割引後の価格",
        "template.discount.price": "元の価格",
        "template.discount.rate": "割引 %",
        "template.discount.explanation": "元の価格に残りの割合を掛けます。",
        "template.compound.title": "複利",
        "template.compound.subtitle": "数年後の将来価値",
        "template.compound.principal": "元本",
        "template.compound.rate": "年率 %",
        "template.compound.years": "年数",
        "template.compound.explanation": "元本に、1 足す年率を年数乗した値を掛けます。",
        "template.loan.title": "ローン返済",
        "template.loan.subtitle": "毎月返済額の目安",
        "template.loan.amount": "借入額",
        "template.loan.rate": "年利 %",
        "template.loan.months": "月数",
        "template.loan.explanation": "標準的な元利均等返済の式で計算します。",
        "template.bmi.title": "BMI",
        "template.bmi.subtitle": "体格指数",
        "template.bmi.weight": "体重 kg",
        "template.bmi.height": "身長 m",
        "template.bmi.explanation": "体重を身長の二乗で割ります。",
        "template.average.title": "平均",
        "template.average.subtitle": "カンマ区切り数値の平均",
        "template.average.values": "数値",
        "template.average.explanation": "合計を個数で割ります。",
        "template.triangle.title": "三角形の面積",
        "template.triangle.subtitle": "底辺と高さ",
        "template.triangle.base": "底辺",
        "template.triangle.height": "高さ",
        "template.triangle.explanation": "底辺に高さを掛け、2 で割ります。",
        "template.speed.title": "速度",
        "template.speed.subtitle": "距離 ÷ 時間",
        "template.speed.distance": "距離",
        "template.speed.time": "時間",
        "template.speed.explanation": "距離を時間で割ります。",
        "convert.title": "単位換算",
        "convert.value": "値",
        "convert.from": "換算元",
        "convert.to": "換算先",
        "convert.category": "カテゴリ",
        "convert.save": "換算を保存",
        "convert.saved": "換算を保存しました。",
        "unit.length": "長さ",
        "unit.weight": "重さ",
        "unit.area": "面積",
        "unit.volume": "体積",
        "unit.temperature": "温度",
        "unit.time": "時間",
        "unit.speed": "速度",
        "unit.meter": "メートル",
        "unit.kilometer": "キロメートル",
        "unit.centimeter": "センチメートル",
        "unit.mile": "マイル",
        "unit.foot": "フィート",
        "unit.kilogram": "キログラム",
        "unit.gram": "グラム",
        "unit.pound": "ポンド",
        "unit.squareMeter": "平方メートル",
        "unit.squareFoot": "平方フィート",
        "unit.acre": "エーカー",
        "unit.liter": "リットル",
        "unit.milliliter": "ミリリットル",
        "unit.gallon": "ガロン",
        "unit.celsius": "摂氏",
        "unit.fahrenheit": "華氏",
        "unit.kelvin": "ケルビン",
        "unit.second": "秒",
        "unit.minute": "分",
        "unit.hour": "時間",
        "unit.mps": "m/秒",
        "unit.kph": "km/時",
        "unit.mph": "mph",
        "plot.title": "関数グラフ",
        "plot.placeholder": "x^2 または sin(x)",
        "plot.range": "x は -10 から 10",
        "plot.draw": "描画",
        "plot.save": "グラフを保存",
        "plot.saved": "グラフを保存しました。",
        "plot.invalid": "x を使う関数を入力してください。",
        "pro.title": "FormulaPad Pro",
        "pro.subtitle": "一度の購入で数式メモをすべて解除。",
        "pro.body": "無制限の履歴、メモ、カスタム式、全テンプレート、グラフ、エクスポートを解除します。",
        "pro.once": "一度きりの購入",
        "pro.loading": "購入項目を読み込み中...",
        "pro.unavailable": "現在購入できません。",
        "pro.owned": "Pro は解除済みです。",
        "pro.restoreDone": "購入を復元しました。",
        "settings.title": "設定",
        "settings.language": "言語",
        "settings.language.auto": "自動",
        "settings.language.en": "English",
        "settings.language.zh": "简体中文",
        "settings.language.ja": "日本語",
        "settings.privacy": "プライバシーポリシー",
        "settings.support": "サポート",
        "settings.contact": "サポートに連絡",
        "settings.version": "バージョン 1.0.0",
        "settings.local": "ローカルデータのみ",
        "share.note": "FormulaPad の計算",
        "error.divideByZero": "0 で割ることはできません。",
        "error.syntax": "式の構文を確認してください。",
        "error.unknownVariable": "不明な変数です。",
        "error.invalidAssignment": "無効な代入です。",
        "error.domain": "値が対応範囲外です。"
    ]
}

